### PR TITLE
adds news to front page

### PR DESCRIPTION
**Pull request by nonmakina**

### CODE REVIEW

**Review by towards-a-new-leftypol — APPROVED** [review]
I hope this doesn't break rebuilds

**Comment by towards-a-new-leftypol** [comment]
Okay the news link on dev leads to a page without stylesheets. I'm guessing news used to be an iframe and was changed to be imported at the template level.

So we need a real news.html page and the current one should be news_content.html or something. Or be lazy and nuke the link to the news from the sidebar.

**Comment by towards-a-new-leftypol** [comment]
Okay the news link on dev leads to a page without stylesheets. I'm guessing news used to be an iframe and was changed to be imported at the template level.

So we need a real news.html page and the current one should be news_content.html or something. Or be lazy and nuke the link to the news from the sidebar.

**Review by towards-a-new-leftypol — CHANGES_REQUESTED** [review]
The reason for blocking this is the link to the news on our homepage, it goes to a very bare, improperly styled page.

**Comment by dedushka1** [comment]
News can be edited at [mod.php?/edit_news](https://github.com/towards-a-new-leftypol/leftypol_lainchan/blob/config/mod.php#L47-L49)

```php
	'/edit_news'				=> 'secure_POST news',		// view news
	'/edit_news/(\d+)'			=> 'secure_POST news',		// view news
	'/edit_news/delete/(\d+)'		=> 'secure news_delete',	// delete from news
```

**Review by towards-a-new-leftypol — APPROVED** [review]

**Pull request merged**
