### PR TITLE
WIP Enables exif stripping.

### LINKED ISSUE #140: Strip exif automatically
```
if ($config['strip_exif']) {
```

### PR DESCRIPTION
**Pull request by nonmakina**
Requires dependencies.

### CODE REVIEW

**Comment by nonmakina** [comment]
Depends on this PR: https://github.com/towards-a-new-leftypol/devops/pull/7

**Comment by nonmakina** [comment]
I haven't tested this yet, nor the added dependency in the devops project.

**Review by Barbara-Pitt — APPROVED** [review]

**Comment by nonmakina** [comment]
I don't have the energy to test these changes unfortunately.

**Comment by discomrade** [comment]
I have added a new pull request in the devops project, with its nix-support-dev/lainchan.nix and this commit active on a dev server. I have confirmed there that .jpg and .jpeg files are being stripped of EXIF data when uploaded.

**Pull request merged**
