### PR TITLE
adds a bunch of more js modules

### LINKED ISSUE #76: Add user options menu
image

related js
```
$config['additional_javascript'][] = 'js/options.js';
$config['additional_javascript'][] = 'js/style-select.js';
$config['additional_javascript'][] = 'js/options/general.js';
$config['additional_javascript'][] = 'js/options/user-css.js';
$config['additional_javascript'][] = 'js/options/user-js.js';
```

### PR DESCRIPTION
**Pull request by nonmakina**

### CODE REVIEW

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/auto-scroll.js';
image

**Comment by nonmakina** [comment]
+$config['additional_javascript'][] = 'js/options/general.js';
+$config['additional_javascript'][] = 'js/options/user-css.js';
+$config['additional_javascript'][] = 'js/options/user-js.js';
image

Moved the webm option so that the tab is at the end.

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/thread-watcher.js';
image
image

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/catalog-search.js';
image

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/gallery-view.js';
image
image

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/expand.js';
"click to expand"
image

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/file-selector.js';
image
I can't post images on the dev instance.

**Comment by nonmakina** [comment]
$config['additional_javascript'][] = 'js/save-user_flag.js';
It works.
image

**Review by towards-a-new-leftypol — APPROVED** [review]

**Pull request merged**
